"""init

Revision ID: 2a2a232e0bcd
Revises: 
Create Date: 2024-12-13 20:42:43.941704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a2a232e0bcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_keeper_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.Enum('RESULT_KEEPER', name='gamename'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_keeper_session_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_keeper_id', sa.Integer(), nullable=False),
    sa.Column('range_min', sa.Integer(), nullable=False),
    sa.Column('range_max', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('started_level', sa.Integer(), nullable=False),
    sa.Column('finished_level', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('finished_datetime', sa.DateTime(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['result_keeper_id'], ['result_keeper_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_keeper_session_table')
    op.drop_table('result_keeper_table')
    # ### end Alembic commands ###