"""add new finished field to GameSession

Revision ID: 56ea8c5c4a98
Revises: 0271476ab9d5
Create Date: 2024-11-27 22:17:05.459919

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56ea8c5c4a98"
down_revision: Union[str, None] = "0271476ab9d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_session", sa.Column("finished", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_session", "finished")
    # ### end Alembic commands ###
