"""add field language to AssociativeChangingSessionModel

Revision ID: a1b3a1fe8fe9
Revises: 27cca1f759b1
Create Date: 2024-12-17 22:01:05.086909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1b3a1fe8fe9'
down_revision: Union[str, None] = '27cca1f759b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associative_changing_session_table', sa.Column('language', sa.Enum('PL', 'EN', name='language'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('associative_changing_session_table', 'language')
    # ### end Alembic commands ###